###
GET http://localhost:3333/ongs

###
POST http://localhost:3333/ongs
content-type: application/json
[
{
    "name":"APAD1",
    "email":"contato@apad.com.br",
    "whatsapp":"47000000000",
    "city":"Rio do Sul",
    "uf":"SC"
}]

###
POST http://localhost:3333/ongs
{
    "name":"APAD2",
    "email":"contato@apad.com.br",
    "whatsapp":"47000000000",
    "city":"Rio do Sul",
    "uf":"SC"
}
